name: .NET_build_to_server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_to_main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server
      working-directory: ./
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'sq009' }}
      run: |
        docker build -t sq009_demo .
        docker tag sq009_demo registry.heroku.com/$APP_NAME/web
        heroku login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
